cloudflare/circl

dh/x25519/doc.go, dh/x448/doc.go
The key validation can mitigate some attacks as such as the ones reported by [Genking-Valenta-Yarom](https://dx.doi.org/10.1145/3133956.3134029)  and [Cremers&Jackson](eprint.iacr.org/2019/526).
=> Key validation

.circleci/config.yml, .etc/golangci.yml, Makefile
Changes:
- Fetching golangci-lint from goreleaser.com brings a version compiled
with go1.12, which once it is run with go1.13 fails.
- Once goreleaser.com build golangci-lint with go1.13, then it can be
restored to the previous fetching method.
- Removing funlen linter, which was added in the latest version.
=> Building golangci-lint during CI using go1.13

.circleci/config.yml, Makefile
* In order to have a stable build we should fix a version
of linters that we use.
* Reverse b1cbc4ca1a5ac879b7b25e8e0c12bf20c12e5580
* Update golangci to 1.18.0 to get support for go 1.13
=> Fix version of linters that CI uses

sign/ed25519/testdata/wycheproof_kat.json
Adds test vectors from [eddsa_test.json](https://github.com/google/wycheproof/blob/master/testvectors/eddsa_test.json) found in wycheproof project.
Merge after #82
=> Updating Wycheproof test vectors to version 0.8rc16.

.circleci/config.yml, README.md, codecov.yml
Closes #19 
Add codecov.io support to circleCI and add badge to Readme.md.
Codecov.io can also be used to display code coverage reports as Pull Request comments.
Example PR Code coverage commit status and Pull-Request comments: https://github.com/dougnukem/circl/pull/1
[![codecov](https://codecov.io/gh/dougnukem/circl/branch/dougnukem/codecov/graph/badge.svg)](https://codecov.io/gh/dougnukem/circl/branch/dougnukem%2Fcodecov)
[![codecov_graph](https://codecov.io/gh/dougnukem/circl/branch/dougnukem/codecov/graphs/tree.svg)](https://codecov.io/gh/dougnukem/circl)
- cloudflare/circl repository admins will need to authorize https://codecov.io/ to access repo
=> add codecov.io to ci and readme badge

internal/shake/sha3.go, internal/shake/xor_generic.go, internal/shake/xor_unaligned.go
The Go runtime assumes that a pointer to a type is aligned on the size
of that type.  We cast a [N]byte to []uint64, which breaks this
assumption.  Thus allocate the original [N]byte as a [N/8]uint64 instead.
Fixes https://github.com/cloudflare/circl/issues/89
Cf. the same issue and patch in upstream:
patch https://go-review.googlesource.com/c/crypto/+/203837/
issue https://github.com/golang/go/issues/35173
=> Align internal SHAKE buffer when using it as []uint64

.circleci/config.yml
Known issues: coverage is failing in go 1.14. 
Merge this after #89 be solved
=> Adding test and build in go 1.14

dh/curve4q/curve4Q.go, dh/curve4q/curve4Q_test.go, ecc/fourq/curve.go, ecc/fourq/curve_test.go, ecc/fourq/fp.go, ecc/fourq/fp_amd64.go, ecc/fourq/fp_amd64.h, ecc/fourq/fp_amd64.s, ecc/fourq/fp_generic.go, ecc/fourq/fp_noasm.go, ecc/fourq/fp_test.go, ecc/fourq/fq.go, ecc/fourq/fq_amd64.go, ecc/fourq/fq_amd64.h, ecc/fourq/fq_amd64.s, ecc/fourq/fq_generic.go, ecc/fourq/fq_noasm.go, ecc/fourq/fq_test.go, ecc/fourq/params.go, ecc/fourq/point.go, ecc/fourq/point_amd64.go, ecc/fourq/point_amd64.h, ecc/fourq/point_amd64.s, ecc/fourq/point_generic.go, ecc/fourq/point_noasm.go, ecc/fourq/point_test.go, ecc/fourq/tableBase.go
Use math.bits package for implementing arithmetic in any architecture.
Includes support for legacy multiplication instructions.
=> Generic implementation of FourQ operations

internal/test/test.go, sign/ed25519/doc.go, sign/ed25519/ed25519.go, sign/ed25519/ed25519_test.go, sign/ed25519/modular.go, sign/ed25519/modular_test.go, sign/ed25519/mult.go, sign/ed25519/point.go, sign/ed25519/point_test.go, sign/ed25519/rfc8032_test.go, sign/ed25519/wycheproof_test.go, sign/ed448/ed448.go, sign/ed448/ed448_test.go, sign/ed448/rfc8032_test.go, sign/ed448/wycheproof_test.go
Changes:
- Unifies the API for EdDSA signatures.
- Both packages implement `crypto.Signer` so it can be used with other signature schemes.
- Added tests for ed25519.
Future changes (not this PR)
- extract edwards25519 arithmetic to the `circl/ecc` package.
=> Updates API for signatures.

sign/dilithium/dilithium_test.go, sign/dilithium/mode3/internal/dilithium.go
A Dilithium private key is generated from three 32 byte seeds: the
public ρ which is used to derive the matrix A, a private seed to
derive the vector s and finally a private seed key to derive the ys.
These three seeds are currently derived from a single 32 byte seed
using SHAKE-128.  On paper (but this is false in this case, see
below) this allows an attacker to compute a collision in 2^128 work.
This would entail two different seeds that generate the same private
key.  In most applications this is not an issue.
It is of great concern whether the two private seeds can be derived from ρ.
Note that it is not sufficient to derive a few bits of the seeds as
these seeds themselves are used as input to hash functions.  Assuming
no weaknesses in SHAKE-128 this would still require trying all …
=> dilithium: NewKeyFromSeed: use SHAKE-256 instead of SHAKE-128

.etc/golangci.yml, .github/workflows/ci-actions.yml, ecc/p384/point.go
It is not encouraged anymore to use `enable-all`, as it will be deprecated and removed soon: https://golangci-lint.run/usage/configuration/
=> Fix linting

sign/eddilithium4/eddilithium.go, sign/eddilithium4/eddilithium_test.go, sign/eddilithium4/example_test.go
Almost the same as eddilithium3 except for generation of the seed (as Ed448 requires more entropy) and the API of ed448.  (ed448 and ed25519 aren't drop-in replacements of eachother, yet.)
=> sign: add hybrid of Dilithium4 and Ed448

sign/dilithium/mode3/internal/sample.go
Speeds up sampling fourway by roughly 10%.
=> dilithium: don't permutate when done

kem/schemes/schemes_test.go, pke/kyber/kyber1024/internal/cpapke.go, pke/kyber/kyber512/internal/cpapke.go, pke/kyber/kyber768/internal/cpapke.go
This wasn't hit in the tests, because the tests of unpacking didn't check
whether the cached A^Ts were the same.
=> kyber: bugfix: compute A^T when unpacking

pke/kyber/internal/common/ntt.go, pke/kyber/internal/common/ntt_test.go, pke/kyber/internal/common/poly.go, pke/kyber/internal/common/poly_test.go, pke/kyber/kyber1024/internal/cpapke.go, pke/kyber/kyber1024/internal/vec.go, pke/kyber/kyber512/internal/cpapke.go, pke/kyber/kyber512/internal/vec.go, pke/kyber/kyber768/internal/cpapke.go, pke/kyber/kyber768/internal/vec.go
InvNTT was more forgiving with its bounds than documented and this was used
in one spot.  After this change InvNTT is less forgiving and so we need
to change that callsite.
Old:
BenchmarkInvNTT-4         431370          2768 ns/op
New:
BenchmarkInvNTT-4         494037          2400 ns/op
=> Kyber: InvNTT: reduce number of Barrett reductions

oprf/group/group.go, oprf/oprf.go, oprf/oprf_test.go
While trying to integrate this API with another library, I found some things that made it somewhat painful to use. I tried to clear those up here. I also added a test to exercise the `KeyPair` serialization logic.
cc @armfazh, @claucece
=> Refactor the OPRF KeyPair interfaces, and add a serialization test.

kem/kem.go, kem/kyber/kat_test.go, kem/kyber/kyber1024/kyber.go, kem/kyber/kyber512/kyber.go, kem/kyber/kyber768/kyber.go, kem/kyber/templates/pkg.templ.go, kem/schemes/schemes_test.go
This reverts the revert.
We don't want that third party input (cipher text for instance) is able to cause a panic.
=> kem: return error instead of panic()ing

oprf/oprf.go, oprf/oprf_test.go
This will make it much easier to serialize OPRF state by callers.
=> Export GroupFromID to facilitate KeyPair serialization and deserialization

kem/kem.go, kem/kyber/kyber1024/kyber.go, kem/kyber/kyber512/kyber.go, kem/kyber/kyber768/kyber.go, kem/kyber/templates/pkg.templ.go, kem/schemes/schemes.go, kem/sike/sikep434/sike.go, kem/sike/sikep503/sike.go, kem/sike/sikep751/sike.go, kem/sike/templates/pkg.templ.go, sign/ed25519/ed25519.go, sign/ed25519/signapi.go, sign/ed448/ed448.go, sign/ed448/signapi.go, sign/eddilithium3/eddilithium.go, sign/eddilithium3/signapi.go, sign/eddilithium4/eddilithium.go, sign/eddilithium4/signapi.go, sign/schemes/schemes.go, sign/sign.go
The registry of algorithms must be read-only, otherwise: 
```go
package main
import (
"fmt"
"github.com/cloudflare/circl/kem/kyber/kyber1024"
"github.com/cloudflare/circl/kem/kyber/kyber512"
)
func main() {
fmt.Println(kyber1024.Scheme.Name())
kyber1024.Scheme = kyber512.Scheme
fmt.Println(kyber1024.Scheme.Name())
}
```
Outputs 
```sh
Kyber1024
Kyber512
```
cc: @bwesterb
=> Use functions for exposing kem and signature schemes

hpke/aead.go, hpke/aead_test.go, hpke/algs.go, hpke/hpke.go, hpke/marshal.go, hpke/marshal_test.go, hpke/util.go, hpke/vectors_test.go
Adds support for HPKE context serialization as required by https://github.com/cloudflare/go/pull/38. The changes are summarized as follows:
- Renames Exporter to Context.
- Adds Suite() and Marshal() to Context interface.
- Adds unmarshalers for the Sealer and Opener implementations.
- Adds validators for cipher suite codepoints.
=> hpke: Add context serialization

go.mod, go.sum, group/group_test.go, group/ristretto255.go, group/ristretto255_test.go
This change wraps @bwesterb's ristretto225 implementation. I'm opening it up as a draft PR to start, since there are some questions I'd like to work through regarding the `Order()` function (see #214). Once we agree on the general design, I'll add tests along the lines of [group_test.go](https://github.com/cloudflare/circl/blob/master/group/group_test.go).
cc @claucece, @wbl
=> Adapt existing ristretto225 implementation to the CIRCL Group interfaces()

.github/workflows/ci-actions.yml, dh/csidh/fp511_amd64.s, dh/sidh/internal/p434/arith_amd64.s, dh/sidh/internal/p503/arith_amd64.s, dh/sidh/internal/p751/arith_amd64.s, pke/kyber/internal/common/amd64.s, pke/kyber/internal/common/asm/src.go, sign/dilithium/internal/common/amd64.s, sign/dilithium/internal/common/asm/src.go, simd/keccakf1600/f1600x.go
Adds go1.16 version for testing.
=> Add go 1.16 version.

oprf/client.go, oprf/oprf.go, oprf/oprf_test.go, oprf/server.go, oprf/vectors_test.go
This implements the [corresponding change](https://github.com/cfrg/draft-irtf-cfrg-voprf/commit/d88e53c61ce7be263fb5e7f9f6beae6ffaac0e6f) in the draft, in preparation for an implementation of public attribute-based VOPRFs.
=> Refactor and generalize the internal proof interfaces.

kem/kyber/kyber1024/kyber.go, kem/kyber/kyber512/kyber.go, kem/kyber/kyber768/kyber.go, kem/kyber/templates/pkg.templ.go, pke/kyber/kyber1024/internal/cpapke.go, pke/kyber/kyber1024/internal/cpapke_test.go, pke/kyber/kyber1024/kyber.go, pke/kyber/kyber512/internal/cpapke.go, pke/kyber/kyber512/internal/cpapke_test.go, pke/kyber/kyber512/kyber.go, pke/kyber/kyber768/internal/cpapke.go, pke/kyber/kyber768/internal/cpapke_test.go, pke/kyber/kyber768/kyber.go, pke/kyber/templates/pkg.templ.go
It fixes a bad parameter passing to pke.EncryptTo function. 
Error wasn't detect as two nested callls both passed parameters in the wrong order. 
Fixes #232
=> kyber: sorting input parameters of EncryptTo function.

dh/sidh/internal/p434/core.go, dh/sidh/internal/p434/curve.go, dh/sidh/internal/p503/core.go, dh/sidh/internal/p503/curve.go, dh/sidh/internal/p751/core.go, dh/sidh/internal/p751/curve.go, dh/sidh/internal/templates/core.gotemp, dh/sidh/internal/templates/curve.gotemp
avoids to copy data when returning from isogeny evaluation.
Updates the template and three instances generated with it.
=> sidh: no return parameter on isogeny EvaluatePoint

.etc/golangci.yml, .github/workflows/ci-actions.yml, pke/kyber/internal/common/field_test.go, pke/kyber/internal/common/ntt_test.go, pke/kyber/internal/common/poly_test.go, sign/dilithium/internal/common/field_test.go, sign/dilithium/internal/common/ntt_test.go, sign/dilithium/internal/common/pack_test.go, sign/dilithium/internal/common/poly_test.go
Bumping up golangci-lint version to v1.41
- replacing invocations of math/rand by crypto/rand
=> Updating linter version to v1.41

ecc/bls12381/constants.go, ecc/bls12381/g1.go, ecc/bls12381/g1_test.go, ecc/bls12381/g2.go, ecc/bls12381/g2_test.go, ecc/bls12381/pair.go, ecc/bls12381/pair_test.go, ecc/bls12381/scalar.go, ecc/bls12381/scalar_test.go
Scalars are represented as a big.Int and can be converted to bytes in little-endian order.
=> bls12381: Includes arithmetic for scalars.

ecc/bls12381/ff/fp.go, ecc/bls12381/g1.go, ecc/bls12381/g1_test.go
This is a provisional (not-constant-time) method for hashing to G1.
A secure implementation must follow the guidelines of https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/
=> Hash to G1 using try-and-increment.

.github/workflows/ci-actions.yml
We should follow go's versioning policy to take advantage of new
library and language features.
=> Remove CI integration for ancient go versions

ecc/bls12381/constants.go, ecc/bls12381/ec2.go, ecc/bls12381/ff/common.go, ecc/bls12381/ff/cyclo6.go, ecc/bls12381/ff/cyclo6_test.go, ecc/bls12381/ff/fp.go, ecc/bls12381/ff/fp12.go, ecc/bls12381/ff/fp12_test.go, ecc/bls12381/ff/fp2.go, ecc/bls12381/ff/fp2_test.go, ecc/bls12381/ff/fp6.go, ecc/bls12381/ff/fp6_test.go, ecc/bls12381/ff/fp_test.go, ecc/bls12381/ff/scalar.go, ecc/bls12381/ff/scalar_test.go, ecc/bls12381/ff/uroot.go, ecc/bls12381/ff/uroot_test.go, ecc/bls12381/g1.go, ecc/bls12381/g1Isog.go, ecc/bls12381/g1_test.go, ecc/bls12381/g2.go, ecc/bls12381/gt.go, ecc/bls12381/hash_test.go, ecc/bls12381/pair.go, ecc/bls12381/pair_test.go, ecc/bls12381/testdata/BLS12381G1_XMD-SHA-256_SSWU_NU_.json, ecc/bls12381/testdata/BLS12381G1_XMD-SHA-256_SSWU_RO_.json
Implements encode and hash to curve as recommended in IETF draft. See https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-11
Removes insecure try-and-increment method for hashing.
Changes:
- Implements encode and hash to curve as recommended in IETF draft.
- G1 ciphersuites for BLS12-381.
- Removes certain memory allocations.
- Adding test vectors for hash to G1.
- Return int rather than bool in ff predicates.
=> bls12: hash to G1 complaint with h2c draft

internal/sha3/sha3.go, internal/sha3/sha3_test.go, internal/sha3/xor.go, internal/sha3/xor_generic.go, internal/sha3/xor_unaligned.go
Two issues prevented the sha3/shake state from staying on the heap:
1. xorIn and copyOut were virtuals (variables)
2. State contains a pointer (buf) into itself
The solution is simple.
For (1) we set xorIn and copyOut at compile-time, which it already was,
but the compiler didn't notice.
For (2) we store the bounds of the original slice buf into storage
instead of the slice itself.
Actual performance benefit doesn't show up properly in this microbenchmark
as it is seen when there is a lot of pressure on the GC:
```
name                   old time/op   new time/op   delta
PermutationFunction-8    375ns ± 7%    375ns ± 9%    ~     (p=0.730 n=5+5)
Sha3_512_MTU-8          8.68µs ± 0%   8.10µs ± 3%  -6.74%  (p=0.008 n=5+5)
Sha3_384_MTU-8          6.27µs ± 1%   6.04µs ± 2%  -3.51%  (p=0.008 …
```
=> sha3: prevent state from escaping to heap

ecc/bls12381/ff/doc.go, ecc/bls12381/ff/fp12cubic.go, ecc/bls12381/ff/fp12cubic_test.go, ecc/bls12381/ff/fp4.go, ecc/bls12381/pair.go
By constructing Fp12 as a cubic over a biquadratic, we can take
advantage of the special form of line function evaluations and save
multiplications inside of the Miller loop. Currently this produces a
6% gain, although further improvements should be possible.
=> Alternative tower for fast pairings

ecc/bls12381/constants.go, ecc/bls12381/ff/common.go, ecc/bls12381/ff/cyclo6_test.go, ecc/bls12381/ff/fp.go, ecc/bls12381/ff/fp12.go, ecc/bls12381/ff/fp12_test.go, ecc/bls12381/ff/fp2.go, ecc/bls12381/ff/fp2_test.go, ecc/bls12381/ff/fp6.go, ecc/bls12381/ff/fp_test.go, ecc/bls12381/ff/scalar.go, ecc/bls12381/ff/scalar_test.go, ecc/bls12381/ff/uroot.go, ecc/bls12381/g1.go, ecc/bls12381/g1_test.go, ecc/bls12381/g2.go, ecc/bls12381/g2_test.go, ecc/bls12381/gt.go, ecc/bls12381/pair.go
Implements the Marshaler interfaces from go stdlib for serialization and deserialization.
Also, Scalar exposes `SetBytes([]byte)` to set scalars using variable-length data.
=> bls12: implements Marshaler interfaces and SetBytes for Scalar

blindsign/blindrsa/blindrsa.go, blindsign/blindrsa/blindrsa_test.go
Before, some messages would contain `|N|-1` bytes, and the spec requires the endpoints to abort in that case. This change ensures that all protocol messages are of the appropriate fixed width.
=> Pad blind RSA protocol messages to fixed modulus width

ecc/p384/opt_test.go, ecc/p384/p384opt.go
Scalars are reduced only when its size in bytes is bigger that the order=N.
There are, however, scalars of such size but larger than N that escaped to be reduced.
With this change, now scalars are fully reduced.
Fixes #312
=> Performs modular reduction for all scalars.

kem/frodo/doc.go, kem/frodo/frodo640shake/frodo.go, kem/frodo/frodo640shake/matrix_shake.go, kem/frodo/frodo640shake/noise.go, kem/frodo/frodo640shake/util.go, kem/frodo/kat_test.go, kem/schemes/schemes.go, kem/schemes/schemes_test.go
=> Added implementation of FrodoKEM-640-SHAKE-CCA.

blindsign/blindrsa/blindrsa.go, blindsign/blindsign.go
This is useful when generating test vectors for applications using this package.
=> Expose randomly generated values for Blind RSA (salt and blind)

oprf/client.go, oprf/keys.go, oprf/oprf.go, oprf/server.go, oprf/vectors_test.go
This is needed so clients can go from `suite` to `group` for serialization functions. Otherwise, clients have to know that, e.g., `oprf.SuiteP384` corresponds to `group.P384`. Now, clients can access the group by `oprf.SuiteP384.Group`.
=> Export Group and Hash for each OPRF suite

group/ristretto255.go, oprf/oprf.go, oprf/oprf_test.go, oprf/vectors_test.go
oprf.SuiteR255 represents the OPRF with Ristretto255 and SHA-512.
=> Enable Ristretto255 for OPRFs.

.github/workflows/ci-actions.yml, ecc/p384/p384_test.go, go.mod, go.sum
Enable CI tests with Go1.18 and moves compatibility pointer to Go1.16
=> Bumping up to Go1.18

dh/sidh/internal/templates/gen.go, kem/kyber/gen.go, kem/kyber/kyber1024/kyber.go, kem/kyber/kyber512/kyber.go, kem/kyber/kyber768/kyber.go, kem/sike/gen.go, pke/kyber/gen.go, sign/dilithium/gen.go
explicit format files because golangci-lint skips auto-generated files. See also https://github.com/golangci/golangci-lint/issues/2864.
=> Formatting auto-generated code.

oprf/oprf.go, oprf/oprf_test.go
We were previously only testing P-256, but it's probably useful to have benchmarks for all suites (to compare and contrast for applications like Privacy Pass).
Benchmarks from my machine are below.
```
✗ go test -bench=.
goos: darwin
goarch: amd64
pkg: github.com/cloudflare/circl/oprf
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkAPI/OPRF_OPRF(ristretto255,_SHA-512)/Client/Request-12         	    8329	    134348 ns/op
BenchmarkAPI/OPRF_OPRF(ristretto255,_SHA-512)/Server/Evaluate-12        	   10000	    117887 ns/op
BenchmarkAPI/OPRF_OPRF(ristretto255,_SHA-512)/Client/Finalize-12        	    6694	    185566 ns/op
BenchmarkAPI/OPRF_OPRF(ristretto255,_SHA-512)/Server/VerifyFinalize-12  	    8535	    137740 ns/op
BenchmarkAPI/OPRF_OPRF(ristretto255,_SHA-512)/Server/FullEvaluate-12 …
```
=> Add benchmarks for all OPRF suites (including a new Ristretto255 suite)

.github/workflows/ci-actions.yml
GitHub Action is sunsetting the macOS 10.15 Actions runner. It will stop working intermittently until being completely removed by 2022-8-30: https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22
=> chore: bump macos runner version

group/group.go, group/ristretto255.go, group/short.go
Adds a method to retrieve the group for elements and scalars. This becomes handy in code and avoids storing the group elsewhere.
=> group: adds a method to retrieve the group.

README.md, dh/sidh/doc.go, dh/sidh/sidh.go, dh/sidh/sike.go, kem/schemes/schemes.go, kem/schemes/schemes_test.go, kem/sike/doc.go, kem/sike/sikep434/sike.go, kem/sike/sikep503/sike.go, kem/sike/sikep751/sike.go, kem/sike/templates/pkg.templ.go
SIDH and SIKE are deprecated as were shown vulnerable to a key recovery attack by Castryck-Decru's paper (https://eprint.iacr.org/2022/975). New systems should not rely on this package. This package is frozen.
Changes:
- package /circl/dh/sidh is deprecated and frozen.
- package /circl/kem/sike is deprecated and frozen.
- package /circl/kem/schemes removes sike from the registry.
=> sidh: deprecates sidh and sike packages.

blindsign/blindrsa/blindrsa_test.go, dh/x25519/key_test.go, dh/x448/key_test.go, ecc/bls12381/hash_test.go, go.mod, go.sum, hpke/vectors_test.go, oprf/vectors_test.go, pke/kyber/gen.go, sign/dilithium/gen.go, sign/ed25519/wycheproof_test.go, sign/ed448/wycheproof_test.go
This PR removes dependency on io/ioutil, since it was deprecated in https://tip.golang.org/doc/go1.16#ioutil
=> Removes dependency on io/ioutil as is deprecated.

.github/workflows/ci-actions.yml, dh/sidh/internal/p434/fp2.go, dh/sidh/internal/p503/fp2.go, dh/sidh/internal/p751/fp2.go, dh/sidh/internal/templates/fp2.gotemp, pke/kyber/gen.go, sign/dilithium/gen.go
CI should fail when code generation is broken.
Now it's fixed, together with the code currently failing.
=> tests: fixes ci to fail fast

dh/sidh/internal/p434/arith_amd64.s, dh/sidh/internal/p434/fp2.go, dh/sidh/internal/p503/fp2.go, dh/sidh/internal/p751/fp2.go, dh/sidh/internal/templates/fp2.gotemp
Updates multiplication method described in:
https://github.com/microsoft/PQCrypto-SIDH/blob/v3.4/src/P434/AMD64/fp_x64_asm.S#L258
Updates reduction method described in:
https://github.com/microsoft/PQCrypto-SIDH/blob/v3.4/src/P434/AMD64/fp_x64_asm.S#L721-L727
=> sidh: updates multiplication and reduction mod p434 

oprf/client.go, oprf/oprf.go, oprf/server.go, oprf/vectors_test.go, zk/dleq/dleq.go, zk/dleq/dleq_test.go
Moves dleq to new top-level zero-knowledge package
=> dleq: Moves dleq to new top-level zero-knowledge package.

ot/simot/simot_test.go, ot/simot/simotlocal.go, ot/simot/simotparty.go
Adds a 1-out-of-2 Oblivious transfer protocol.
Implements the SimplestOT by Chou, Orlandi (https://eprint.iacr.org/2015/267.pdf , the 1 out of 2 OT case).
=> SimplestOT: 1-out-of-2 Oblivious Transfer

group/group.go, group/ristretto255.go, group/short.go
This change enables one to set Scalars to integer values encapsulated in big.Int types. Previously, only uint64 inputs were admitted.
=> Add Scalar/SetBigInt function

blindsign/blindrsa/blindrsa.go, blindsign/blindrsa/blindrsa_test.go, blindsign/blindsign.go
This is necessary for some prototyping work in PPM.
I also updated the blind signer `Verifier` interface to implement the signature verification routine, as before it was assumed that the caller would know the internal details of how to verify signatures produced using a verifier.
=> Add deterministic blind RSA verifier

.github/workflows/ci-actions.yml, Makefile
CodeQL scans for known vulnerabilities in code.
=> Adding CodeQL analyzer

CITATION.cff, README.md
On preparation for bumping up to v1.3.0
=> Updating readme for v1.3.0.

tss/rsa/keyshare.go, tss/rsa/rsa_threshold.go, tss/rsa/rsa_threshold_test.go, tss/rsa/signShare.go
As per [RFC 8017 Section 8.2.2](https://www.rfc-editor.org/rfc/rfc8017#section-8.2.2)
> If the length of the signature S is not k octets (where k is the length in octets of the RSA modulus n), output "invalid signature" and stop.
=> tss/rsa: Fixes RSA signature size.

pke/kyber/internal/common/params/params.go
These two constants are unnecessarily typed. This flows through all the way to the kem/kyber/kyberN packages where they cause `PrivateKeySize` and `PublicKeySize` to also be unnecessarily typed.
=> Use untyped consts for Kyber params

zk/dl/dl.go, zk/dl/dl_test.go
Adds some length-prefixed labels.
Fixes #390
=> zk/dl: adds prefixed labels and updates nomenclature.

cipher/ascon/ascon.go, cipher/ascon/ascon_test.go
* Updating code points for Modes.
* Check the cipher.AEAD interface works as expected. 
* The interface allows to reuse the plaintext to store the ciphertext.
=> ascon: update formulas and check for API compatibility

.etc/all_imports.go, .github/workflows/ci-actions.yml, Makefile, abe/cpabe/doc.go, abe/doc.go, cipher/doc.go, dh/csidh/fp511_amd64.s, dh/sidh/internal/p434/arith_amd64.s, dh/sidh/internal/p503/arith_amd64.s, dh/sidh/internal/p751/arith_amd64.s, ecc/fourq/fq_amd64.h, ecc/p384/arith_amd64.s, math/fp25519/fp_amd64.h, math/fp448/fp_amd64.h, ot/doc.go, tss/doc.go, zk/doc.go
**Issue:** CIRCL cannot be compiled as a plugin, i.e., cannot be dynamically linked.
Fixes #391 
Adds a CI job that checks whether CIRCL can be compiled using `-buildmode=plugin`.
When compiling, the compiler shows errors such as:
```sh
asm: arith_amd64.s:2450: when dynamic linking, R15 is clobbered by a global variable access and is used here
ADCQ AX, R15
MULXQ AX, R15, BX
MULXQ AX, BX, R15
```
**Why?**: The main reason is that Go compiler uses R15 to access to global variables, so it alters its value (do not restore it).
There are two solutions: 
1. reduce the use of global variables when possible. (In our case, some global variables store constant values, which can be replaced by immediate addressing. e.g. `MOV $0x22434, AX`)
2. make sure R15 is not used after accessing a global …
=> all: enables dynamic linking, removes R15 is clobbered

abe/cpabe/tkn20/tkn20.go
Both SystemSecretKey.KeyGen and Setup try to dereference the return values from abe/cpabe/tkn20/internal/tkn without checking for an error. On error, these values are nil and the functions panic.
This is easy to reproduce by passing an io.Reader that returns an error.
=> tkn20: prevent panics on key gen errors

abe/cpabe/tkn20/internal/tkn/util.go, expander/expander.go
These are both called when the blake2b.XOF / hash.Hash has just been freshly created.
=> expander,tkn20: remove superfluous Reset calls

.github/workflows/ci-actions.yml, go.mod, go.sum
CIRCL does not necessarily depend on newer x/crypto and x/sys versions. Lower the version requirements to match Go 1.20.2, this avoids the need to upgrade stdlib dependencies when integrating circl.
While at it, bump golangci-lint and drop Go 1.18 which is no longer supported by Go developers.
=> Reduce x/crypto and x/sys versions to match Go 1.20

cipher/ascon/ascon.go, cipher/ascon/ascon_test.go
Fixes #415
cc @bwesterb @armfazh
=> Make ascon cipher go routine safe

abe/cpabe/tkn20/internal/tkn/bk.go, blindsign/blindrsa/blindrsa.go, go.mod, go.sum, kem/frodo/frodo640shake/frodo.go, kem/kyber/kyber1024/kyber.go, kem/kyber/kyber512/kyber.go, kem/kyber/kyber768/kyber.go, kem/kyber/templates/pkg.templ.go, kem/sike/sikep434/sike.go, kem/sike/sikep503/sike.go, kem/sike/sikep751/sike.go, kem/sike/templates/pkg.templ.go
In practice crypto/rand.Read never returns an error, but that is not guaranteed. Check for those errors.
In contrast to crypto/rand.Reader, a user-provided io.Reader, might not fill the buffer without returning an error. Though marginal, we should deal with that corner-case as well.
=> Check for crypto/rand errors and ReadFull io.Readers

hpke/hpke_test.go
These benchmarks let one quickly compare the cost difference between two different HPKE ciphersuites (KEM, KDF, AEAD).
Here's a sample of the output when running the benchmarks (`go test -bench=.`) in the HPKE directory:
```
✗ go test -bench=.
goos: darwin
goarch: arm64
pkg: github.com/cloudflare/circl/hpke
BenchmarkHpkeRoundTrip/SetupSender-0020-0001-0001-10         	   18325	     65444 ns/op
BenchmarkHpkeRoundTrip/SetupReceiver-0020-0001-0001-10       	   28868	     41394 ns/op
BenchmarkHpkeRoundTrip/Encrypt-0020-0001-0001-10             	14436075	        84.96 ns/op
BenchmarkHpkeRoundTrip/Decrypt-0020-0001-0001-10             	14667714	        83.58 ns/op
BenchmarkHpkeRoundTrip/SetupSender-0030-0001-0001-10         	   13032	     91840 ns/op …
```
=> Add HPKE benchmarks

internal/sha3/sha3.go, internal/sha3/shake.go, xof/k12/k12.go, xof/k12/k12_test.go
On M2 Pro:
```
goos: darwin
goarch: arm64
pkg: github.com/cloudflare/circl/xof/k12
BenchmarkK12_100B-12    	 5237684	       225.1 ns/op	 444.26 MB/s
BenchmarkK12_10K-12     	  106761	     11281 ns/op	 886.45 MB/s
BenchmarkK12_100K-12    	   26758	     44659 ns/op	2239.19 MB/s
BenchmarkK12_1M-12      	    3723	    324025 ns/op	3086.18 MB/s
BenchmarkK12_10M-12     	     384	   3107586 ns/op	3217.93 MB/s
PASS
ok  	github.com/cloudflare/circl/xof/k12	7.254s
```
For comparison:
```
goos: darwin
goarch: arm64
pkg: github.com/cloudflare/circl/internal/sha3
BenchmarkPermutationFunctionTurbo-12    	 7788294	       145.3 ns/op	1376.86 MB/s
BenchmarkTurboShake128_1MiB-12          	    1159	   1027718 ns/op	1020.29 MB/s
BenchmarkTurboShake256_1MiB-12          	     945	   1255741 ns/op	 835.03 MB/s …
```
=> Kangaroo12 draft -10

xof/k12/k12.go
=> xof/k12: Fix a typo in the package documentation

abe/cpabe/tkn20/bench_test.go
Adds tkn20 benchmarks comparing operation performance (key generation, encryption, decryption) against RSA-PKCSv1 and X25519. Two policy/attribute lengths are compared-- one is small (2 attributes), another is 50 attributes. 
Sizes of ciphertexts and keys is also compared.
=> Add tkn20 benchmarks

.github/workflows/ci-actions.yml
Bumping up to versions 1.21 and 1.20
=> Bumping Go version for CI jobs.

CITATION.cff, README.md
Updating readme with new algorithms.
Bumping to v1.3.6 to jump branch tags.
=> Releasing CIRCL v1.3.6

pke/kyber/internal/common/poly.go, pke/kyber/internal/common/poly_test.go
On some platforms, division by q leaks some information on the ciphertext by its timing. If a keypair is reused, and an attacker has access to a decapsulation oracle, this reveals information on the private key. This is known as "kyberslash2".
Note that this does not affect to the typical ephemeral usage in TLS.
=> kyber: remove division by q in ciphertext compression

ecc/bls12381/ff/cyclo6.go, ecc/bls12381/ff/cyclo6_test.go, ecc/bls12381/ff/fp12cubic.go, ecc/bls12381/ff/fp12cubic_test.go, ecc/bls12381/ff/fp4.go, ecc/bls12381/pair.go
Implement faster squaring by Granger-Scott.
See Page 7 of https://www.iacr.org/archive/pkc2010/60560212/60560212.pdf
```
BenchmarkFinalExpo/HardExp-16      1869311       1186504       -36.53%
BenchmarkFinalExpo/FinalExp-16     1941307       1283443       -33.89%
BenchmarkPair/Pair-16              2879087       2203070       -23.48%
BenchmarkPair/ProdPair3-16         10354636      9508109       -8.18%
```
=> Implement Granger-Scott faster squaring in the cyclotomic subgroup.

group/group.go, group/group_test.go, group/ristretto255.go, group/short.go
There is no point in returning a `Scalar` for Order method.
Also, returning a big.Int is not desirable.
Since the group order is public and well-know for the groups supported, then it's better to remove the method.
Based on top of: #355  (merge that first)
Fixes #214
=> group: removes order method from group interface

README.md, zk/qndleq/qndleq.go, zk/qndleq/qndleq_test.go
This is required to enable verification of shares in threshold RSA.
=> zk/dleq: Adding DLEQ proofs for Qn, the subgroup of squares in (Z/nZ)*

.etc/golangci.yml, .github/workflows/ci-actions.yml, blindsign/blindrsa/brsa_test.go, blindsign/blindrsa/internal/common/rsa.go, go.mod, pke/kyber/internal/common/asm/go.mod, sign/dilithium/internal/common/asm/go.mod
* Use latest macOS and Windows versions instead of referring to an outdated version that might be removed later. See the table at https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
* Use the `stable` and `oldstable` aliases instead of hard-coding specific point releases for `actions/setup-go`. The arm64 builder is using a Docker image, so use the `1.22` image tag. We can use the `latest` tag in the future to avoid having to update the version.
* Bump `github/codeql-action` actions to v3 as v2 is deprecated: https://github.com/github/codeql-action?tab=readme-ov-file#supported-versions-of-the-codeql-action
* Bump Go version in go.mod to the minimum Go version supported …
=> Bump GitHub Actions versions and use Go 1.22 and 1.21

.github/workflows/ci-actions.yml
Report from CodeQL
```
Newer Go version needed
[View workflow run](https://github.com/cloudflare/circl/actions/runs/7938355244)
Version v1.20.14 of Go is installed, but this is lower than v1.21 required by your project's go.mod. [Install a newer version of Go before analyzing your project](https://github.com/actions/setup-go#basic).
```
=> Explicitly installs Go with version before CodeQL analysis.

.github/workflows/ci-actions.yml
Bumps golangci-lint action so it fixes errors on the node version used internally.
=> Bumps golangci-lint action

ecc/bls12381/g1.go, ecc/bls12381/g1_test.go, ecc/bls12381/pair.go, ecc/bls12381/pair_test.go
Issue: Pairing functions internally convert input points to affine, overwriting the input. This causes troubles in a multiple goroutine scenario.
Fix: Ensures pairing operations don't overwrite the input.
Added a test for checking input's integrity.
Fixes #493
=> ecc/bls12381: Ensures pairing operations don't overwrite their input

sign/eddilithium3/eddilithium.go
=> eddilithium3: fix typos

kem/kem.go, kem/kyber/templates/pkg.templ.go, kem/mlkem/mlkem1024/kyber.go, kem/mlkem/mlkem512/kyber.go, kem/mlkem/mlkem768/kyber.go
Described in section 7.3 of FIPS 203.
The check is only required if the private key is from an untrusted source. We do not distinguish between a trusted and untrusted source in the current API, so we'll perform the check every time we unmarshal the private key.
=> Add ML-KEM decapsulation key check.

.github/workflows/ci-actions.yml, CITATION.cff, README.md
Releasing version v1.4.0
Including FIPS 203 ML-KEM algorithm.
=> Preparing for release v1.4.0

sign/dilithium/templates/acvp.templ.go, sign/dilithium/templates/pkg.templ.go, sign/mldsa/mldsa44/acvp_test.go, sign/mldsa/mldsa44/dilithium.go, sign/mldsa/mldsa65/acvp_test.go, sign/mldsa/mldsa65/dilithium.go, sign/mldsa/mldsa87/acvp_test.go, sign/mldsa/mldsa87/dilithium.go
Adds testing for internal verification function.
Closes #516
=> sign/mldsa: Add test for ML-DSA signature verification.

hpke/algs.go, hpke/genericnoauthkem.go, hpke/hpke.go, hpke/hpke_test.go, kem/schemes/schemes.go, kem/schemes/schemes_test.go, kem/xwing/scheme.go, kem/xwing/xwing.go, kem/xwing/xwing_test.go
Implementation of [X-Wing PQ/T hybrid](https://datatracker.ietf.org/doc/draft-connolly-cfrg-xwing-kem/).
=> X-Wing PQ/T hybrid

kem/hybrid/ckem.go
> TODO move over to crypto/ecdh once we can assume Go 1.20.
I found that there is an unfinished TODO in `ckem.go`, and the go version we use now is higher than 1.20.
Due to the limited code using crypto/ecdh in the entire repository, I can only go by my own experience with the transition, so some of the implementations may not be so satisfying.
This also help fix some problem of 
> TODO: replace deprecated elliptic.Marshal, elliptic.GenerateKey,
> elliptic.Unmarshal, params.ScalarBaseMult before re-enabling SA1019.
in circl/.golangci.yaml
=> ckem: move crypto/elliptic to crypto/ecdh

vdaf/prio3/arith/arith.go, vdaf/prio3/arith/fp128/poly.go, vdaf/prio3/arith/fp128/vector.go, vdaf/prio3/arith/fp64/poly.go, vdaf/prio3/arith/fp64/vector.go, vdaf/prio3/arith/poly_test.go, vdaf/prio3/arith/templates/poly.go.tmpl, vdaf/prio3/arith/templates/vector.go.tmpl, vdaf/prio3/internal/flp/flp.go
prio3: Adds polynomial multiplication using NTT.
=> prio3: Adds polynomial multiplication using NTT

kem/hybrid/ckem.go, kem/hybrid/xkem.go, kem/hybrid/xkem_test.go, kem/xwing/xwing.go
X25519 public keys with low order points result in an all-zeroes shared secret. Ensure that hybrids with X25519 and X448 fail during Encapsulate and Decapsulate when the peer provides such a garbage public key.
___
I discovered this while rebasing our Go fork on Go 1.24 which upgraded the BoGo test suite as part of implementing X25519MLKEM768: https://github.com/golang/go/commit/4b7f7cd87dfcbc17861c908b20a6101e5915ef59#diff-db7320adf5b82005863ef324a30e91235d0268afe79856722226022f3afc2611
That upgrade pulled in this change that adds extra tests for key shares: https://github.com/google/boringssl/commit/ed95627d2f074b6a8636fc8eaaa595903dbfcc9
Without this fix, these `crypto/tls` tests would fail as the TLS handshake continues instead of aborting:
``` …
```
=> kem/hybrid: ensure X25519 hybrids fails with low order points

.github/workflows/ci-actions.yml
The QEMU builder sporadically crashes in gcc. Since there are now native ARM64 build agents available, use that instead. Re-enable Go 1.23 for ARM64, the original Go 1.23 incompatibility with QEMU got resolved.
___
This should prevent flaky builds such as:
- https://github.com/cloudflare/circl/actions/runs/13960263989/job/39080251377 (#540)
- https://github.com/cloudflare/circl/actions/runs/13989058956/job/39168905189 (#541)
=> .github: Use native ARM64 builders instead of QEMU

dh/curve4q/curve4Q.go, dh/curve4q/curve4Q_test.go, ecc/fourq/curve.go, ecc/fourq/point.go, ecc/fourq/point_test.go, ecc/goldilocks/curve.go, ecc/goldilocks/point_test.go, sign/ed25519/point.go, sign/ed25519/point_test.go
Changes: 
- Fixes validation of points (`IsOnCurve` and `IsEqual` methods) over a twisted Edwards curve. It applies to FourQ, Ed25519 and goldilocks curves.
- Detection of Low Order points for Curve4q DH. 
- Fixes Unmarshalling of FourQ points.
Each pair of commits is 1 test and 1 fix.
=> Fixes several errors on twisted Edwards curves.

.github/workflows/ci-actions.yml, .golangci.yaml, CITATION.cff, README.md
=> Release v1.6.1

ecc/bls12381/pair.go
What the title says. :) This version passes all tests and is approximately 2x faster in the benchmarks.
A shorter but slightly slower alternative can be found below. This is joint work with @aniagut.
```
// ProdPair calculates the product of pairings, i.e., \Prod_i pair(ni*Pi,Qi).
func ProdPair(P []*G1, Q []*G2, n []*Scalar) *Gt {
if len(P) != len(Q) || len(P) != len(n) {
panic("mismatch length of inputs")
}
mi := new(ff.Fp12)
out := new(ff.Fp12)
out.SetOne()
affineP := affinize(P)
for i := range affineP {
affineP[i].ScalarMult(n[i], &affineP[i]);
affineP[i].toAffine();
miller(mi, &affineP[i], Q[i])
out.Mul(out, mi)
}
e := &Gt{}
finalExp(e, out)
return e
}
```
=> Optimize pairing product computation by moving exponentiations to G1.

sign/internal/dilithium/arm64.go, sign/internal/dilithium/arm64.s
To test performance difference on arm64 chips: "go test -benchmem -run=^$ ./sign/internal/dilithium -bench=MulBy2"
On my machine (Apple M1 Max) on average:
```
BenchmarkMulBy2toDGeneric-10            13260348                88.91 ns/op            0 B/op          0 allocs/op
BenchmarkMulBy2toD-10                   78609487                15.04 ns/op            0 B/op          0 allocs/op
```
Also consider this are microbenchmarks!
=> add arm64 version of polyMulBy2toD

sign/internal/dilithium/arm64.go, sign/internal/dilithium/arm64.s
To test performance difference on arm64 chips: "go test -benchmem -run=^$ ./sign/internal/dilithium -bench=Sub"
On my machine (Apple M1 Max) on average:
```
BenchmarkSubGeneric-10          12127086                89.72 ns/op            0 B/op          0 allocs/op
BenchmarkSub-10                 56654660                20.93 ns/op            0 B/op          0 allocs/op
```
Also consider this are microbenchmarks!
=> add arm64 version of polySub
