cloudflare/circl

README.md

This defines our policy for versioning. Next will be releasing v0.0.1

Add a versioning policy

---

ecc/p384/api_test.go
ecc/p384/p384.go
ecc/p384/p384_test.go

This change allows that ECDSA verification uses a faster method.
Fixes #63

Renaming SimulteanousMult to CombinedMult

---

ecc/fourq/point_test.go
ecc/p384/api_test.go
ecc/p384/p384_test.go
ecc/p384/point_test.go

With this PR, the Go report card has a 100% score on govet and gocyclo.

Fixes a go vet issue and reduces cyclomatic complexity of some tests

---

dh/csidh/fp511_generic.go
dh/sidh/internal/p434/arith_generic.go
dh/sidh/internal/p503/arith_generic.go
dh/sidh/internal/p751/arith_generic.go
dh/sidh/internal/templates/arith_generic.gotemp

This just cleans the code a little.

Remove some unused assignements

---

.github/workflows/ci-actions.yml

Makes use of [codecov-action](https://github.com/codecov/codecov-action)

Uses a github action for uploading coverage report.

---

sign/dilithium/internal/common/amd64.go
sign/dilithium/internal/common/amd64.s
sign/dilithium/internal/common/asm/src.go
sign/dilithium/internal/common/generic.go
sign/dilithium/internal/common/poly.go
sign/dilithium/internal/common/poly_test.go
sign/dilithium/internal/common/stubs_amd64.go

- AVX2 & POPCNT optimised MakeHint

Dilithium: optimized MakeHint

---

sign/dilithium/dilithium.go
sign/dilithium/mode1.go
sign/dilithium/mode1/dilithium.go
sign/dilithium/mode1aes.go
sign/dilithium/mode1aes/dilithium.go
sign/dilithium/mode2.go
sign/dilithium/mode2/dilithium.go
sign/dilithium/mode2aes.go
sign/dilithium/mode2aes/dilithium.go
sign/dilithium/mode3.go
sign/dilithium/mode3/dilithium.go
sign/dilithium/mode3aes.go
sign/dilithium/mode3aes/dilithium.go
sign/dilithium/mode4.go
sign/dilithium/mode4/dilithium.go
sign/dilithium/mode4aes.go
sign/dilithium/mode4aes/dilithium.go
sign/dilithium/templates/mode.templ.go
sign/dilithium/templates/modePkg.templ.go
sign/eddilithium3/eddilithium.go
sign/eddilithium3/eddilithium_test.go
sign/eddilithium3/example_test.go

I'll add EdDilithium4 (which would be Dilithium4 + Ed448) when we're happy with this one.

eddilithium3: add hybrid of Dilithium3 and Ed25519

---

pke/kyber/internal/common/ntt.go

Reverse engineered from 2c526f65bf43606a8d19f1a9d22b752b16c388b6
on https://github.com/pq-crystals/kyber.  I see no change in performance.
This trick will be used in the AVX2 optimised version, so it's nice to keep the reference implementation close to that.

kyber: ntt: get rid of InvZetas table

---

pke/kyber/internal/common/sample.go
pke/kyber/internal/common/sample_test.go

benchmark                   old ns/op     new ns/op     delta
BenchmarkDeriveNoise2-4     1343          1045          -22.19%
BenchmarkDeriveNoise3-4     2039          1532          -24.87%

kyber: DeriveNoise: optimize for 64 bits

---

oprf/oprf.go
oprf/oprf_test.go

Export some missing OPRF pieces. Clean up unit tests.

---

hpke/aead_test.go

Addresses the comment [here](https://github.com/cloudflare/circl/pull/203#discussion_r546249281).

Add HPKE Open and Seal phase mismatch tests.

---

oprf/keys.go
oprf/oprf.go
oprf/vectors_test.go

Adding a function for deriving keys deterministically.

DeriveKey for deterministically deriving keys from a seed.

---

hpke/hpke.go
hpke/vectors_test.go

This only changes the version tag and test vectors.

Update HPKE to v08.

---

group/group.go
group/group_test.go
group/ristretto255.go
group/short.go
oprf/oprf.go
oprf/oprf_test.go

Exposes the bytesize of group elements and scalars.

group, oprf: Exposes bytesize of group elements and scalars

---

oprf/oprf_test.go

Adding benchmark functions to OPRF package

Adding benchmark functions to OPRF package

---

ecc/bls12381/ff/fp.go
ecc/bls12381/ff/fp12.go
ecc/bls12381/ff/fp12_test.go
ecc/bls12381/ff/fp2.go
ecc/bls12381/ff/fp2_test.go
ecc/bls12381/ff/fp6.go
ecc/bls12381/ff/fp_test.go
ecc/bls12381/g1.go
ecc/bls12381/g1_test.go
ecc/bls12381/g2.go
ecc/bls12381/g2_test.go
ecc/bls12381/gt.go

G2 deserialization is quite expensive unfortunately. This should
complete the functions callers will need, although some improvements
to efficiency could still be made.

Point serialization

---

ecc/bls12381/g1_test.go
ecc/bls12381/g2_test.go
ecc/bls12381/pair_test.go
ecc/bls12381/scalar.go
ecc/bls12381/scalar_test.go

Accepting a user specified random source enables the easy construction
of PRFs, deterministic key generation etc.

Change signature of Random function

---

ecc/bls12381/constants.go
ecc/bls12381/g1.go
ecc/bls12381/g1_test.go
internal/test/test.go

Implements method described in https://eprint.iacr.org/2019/814.pdf

bls12: adding efficient subgroup checking method for G1

---

hpke/aead.go
hpke/algs.go
hpke/hpke.go
hpke/marshal.go
hpke/shortkem.go
hpke/xkem.go

hpke: exporting errors

---

ecc/bls12381/constants.go
ecc/bls12381/ff/common.go
ecc/bls12381/ff/cyclo6.go
ecc/bls12381/ff/cyclo6_test.go
ecc/bls12381/ff/doc.go
ecc/bls12381/ff/fp.go
ecc/bls12381/ff/fp12.go
ecc/bls12381/ff/fp2.go
ecc/bls12381/ff/fp6_test.go
ecc/bls12381/ff/scalar.go
ecc/bls12381/g1.go
ecc/bls12381/g1_test.go
ecc/bls12381/g2.go
ecc/bls12381/g2_test.go
ecc/bls12381/gt.go
ecc/bls12381/hash_test.go
ecc/bls12381/psi_test.go
go.mod
go.sum
internal/conv/conv.go

These changes are needed to accomplish #257 .

bls12: changing serialization of Fp to big-endian format

---

ecc/bls12381/constants.go
ecc/bls12381/ec2.go
ecc/bls12381/ff/cyclo6.go
ecc/bls12381/ff/cyclo6_test.go
ecc/bls12381/ff/fp.go
ecc/bls12381/ff/fp12.go
ecc/bls12381/ff/fp12_test.go
ecc/bls12381/ff/fp2.go
ecc/bls12381/ff/fp2_test.go
ecc/bls12381/ff/fp6.go
ecc/bls12381/ff/fp6_test.go
ecc/bls12381/ff/fp_test.go
ecc/bls12381/ff/uroot.go
ecc/bls12381/ff/uroot_test.go
ecc/bls12381/g1.go
ecc/bls12381/g1Isog.go
ecc/bls12381/g1_test.go
ecc/bls12381/g2.go
ecc/bls12381/g2_test.go
ecc/bls12381/gt.go
ecc/bls12381/pair.go
ecc/bls12381/pair_test.go
ecc/bls12381/psi_test.go

using native copy functions rather than using a setter function.

bls12: removing Set functions

---

pke/kyber/internal/common/asm/src.go
sign/dilithium/internal/common/asm/src.go
simd/keccakf1600/internal/asm/src.go

This reverts commit 3a9a68d7e373f25a0025c2b0c98d730274120c08.
Fixes #284

Revert "Add +build ignore tag to ASM generators"

---

ecc/bls12381/ff/cyclo6.go
ecc/bls12381/ff/cyclo6_test.go
ecc/bls12381/ff/fp12.go
ecc/bls12381/ff/fp12_test.go
ecc/bls12381/ff/fp6.go
ecc/bls12381/ff/uroot.go
ecc/bls12381/ff/uroot_test.go
ecc/bls12381/gt.go
ecc/bls12381/gt_test.go
ecc/bls12381/pair.go
ecc/bls12381/pair_test.go

Gt.Exp using fixed-window exponentiation method.

bls12: Gt Exp using fixed-window exponentiation method.

---

.etc/action.awk
.github/workflows/ci-actions.yml
dh/sidh/internal/p434/fp2_test.go
dh/sidh/internal/p503/fp2_test.go
dh/sidh/internal/p751/fp2_test.go
dh/sidh/internal/templates/fp2_test.gotemp

Removes a shadowed variable detected by #291

sidh: removes a shadowed variable

---

blindsign/blindrsa/blindrsa_test.go

Verify the signatures for sanity's sake

---

oprf/client.go
oprf/oprf.go
oprf/oprf_test.go
oprf/server.go
oprf/vectors_test.go

... along with function to copy an evaluation requests's blind values.

Add deterministic Blind function 

---

.github/workflows/ci-actions.yml

Wait for amd64 job succeds to run other jobs.

---

group/group.go
group/group_test.go
group/ristretto255.go
group/short.go

Document operations of the group interface.
Based on top of #353 (merge that first).

group: document group interface

---

group/group.go
group/group_test.go
group/ristretto255.go
group/short.go
math/polynomial/polynomial.go
math/polynomial/polynomial_test.go

adds polynomials and Lagrange polynomials to be used in secret sharing package

math: adds polynomials and Lagrange polynomials.

---

sign/dilithium/internal/common/params/params.go

dilithium: fix typo

---

.etc/golangci.yml
.github/workflows/ci-actions.yml
hpke/aead_test.go
hpke/algs.go

Bumping linter to v1.49

---

zk/dl/dl.go
zk/dl/dl_test.go

NIZK proof of knowledge of a scalar k given two points kG and G.
This is the Schnorr proof as described in [RFC823](https://datatracker.ietf.org/doc/html/rfc8235#page-6)

NIZK Schnorr proof

---

abe/cpabe/tkn20/testdata/serialize.go

Temporary workaround for #385.

tkn20: Don't build outdated source file

---

.etc/golangci.yml
.github/workflows/ci-actions.yml
go.mod
go.sum

Moving to Go 1.20
~This is not ready until golint bug is solved: https://github.com/golangci/golangci-lint/pull/ 3414~

Bumping Go version.

---

go.mod
go.sum

Updates to the latest stdlib versions.
Related: https://go-review.googlesource.com/c/go/+/471256

Updating stdlib crypto library.

---

math/primes.go
math/primes_test.go
tss/doc.go
tss/rsa/rsa_threshold.go
tss/rsa/rsa_threshold_test.go

Includes a method that generates RSA keys where the modulus is the product of two safe prime numbers.

tss/rsa: key generation for threshold RSA (safe primes)

---

CITATION.cff
README.md

New release that includes patch to Kyber

Releasing CIRCL v1.3.7

---

.etc/golangci.yml
pke/kyber/internal/common/asm/go.sum
sign/dilithium/internal/common/asm/go.sum

- fix threshold for constant values.
- go mod tidy inside the /asm folders.

Adding rule for constant values

---

CITATION.cff
README.md

Preparing CIRCL release v1.3.9

Preparing CIRCL release v1.3.9

---

CITATION.cff
README.md

Release v1.5.0

---

.github/workflows/semgrep.yml

Disables semgrep job in forked repos.

Run semgrep cronjob only in upstream repository.

---

CITATION.cff
README.md

Adds Prio3 to readme documentation.

Add Prio3 in readme.
